# Sethtoken <sethtoken.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAWKAOLECPZWJM3AYLCNZZ7IAYSSDFLOBGO3QKUXL4OS7QKJDQTEAARO"
]

[DOCUMENTATION]
ORG_NAME="Sethtoken"
ORG_URL="https://sethtoken.github.io"
ORG_LOGO = "https://sethtoken.github.io/img/seth.png"
ORG_OFFICIAL_EMAIL="tokenofseth@gmail.com"
ORG_SUPPORT_EMAIL="tokenofseth@gmail.com"
ORG_TWITTER="tokenofseth"
ORG_DESCRIPTION="Sethtoken: Create Value to Meme Coin Space"

[[PRINCIPALS]]
email="tokenofseth@gmail.com"

[[CURRENCIES]]
code = "SETH"
name = "SETH"
issuer = "GAWKAOLECPZWJM3AYLCNZZ7IAYSSDFLOBGO3QKUXL4OS7QKJDQTEAARO"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of SETH"
image="https://sethtoken.github.io/img/seth.png"
conditions="There will only ever be 1 billion SETH tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
